### ISSUE TITLE
[New Feature] make yaml_object decorator available

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-core#66]
### Feature Description

Turn the `YAML()` instance used by `yaml_load` and `yaml_dump` into some kind of singleton and make it available to all qudi modules. This allows to register new classes with the YAML instance and thereby loading and dumping of arbitrary objects. The nicest way for qudi might be to use the [`yaml_object`](https://yaml.readthedocs.io/en/latest/dumpcls.html) decorator.

### Related Problem

YAML is used to dump and load status variables. This only supports certain built-in types, e.g. `dict`. Special data classes need to be converted to some built-in type beforehand. I specifically ran into this need while trying to refactor parts of `scanning_probe_interfuse`. Here, different types of dataclasses are or could be nested into each other. Writing dict representers for all of them is cumbersome and produces an avoidable overhead.

### Considered Alternatives

It could also be possible to somehow just let the core know of any classes you want to register with the YAML instance. The YAML instance can then be generated as usual during dumping/loading and the registering can happen each time.

**Comment by qku** [comment]
Actually the `yaml_object` decorator is enough to make things work. I did not need to implement representer or constructor methods.

I understand your concerns on opening up what classes can be dumped/loaded. Adding native support for all dataclasses doesn't work however as [dataclasses](https://docs.python.org/3/library/dataclasses.html) only

> provides a decorator and functions for automatically adding generated special methods [...] to user-defined classes

i.e. they don't represent a type by themselves.

My specific case is actually at least close to the fear you are describing I believe: there is a scan history StatusVar in the confocal scanner of qudi-iqo-modules which dumps a list of `ScanData` instances. I will look into what actually needs to be saved here and what is unnecessary.

**Comment by Neverhorst** [comment]
I just had a deeper look into the `yaml_object` implementation and realized a few things:
- dumping a decorated object will simply pass the objects `__dict__` attribute to the regular dumper. This will fail in many cases for objects that are not simple data classes. It will also dump information that might not be necessary or simply invoke unexpected behaviour of the object when loading the object from file. In general, you should only dump information necessary to initialize the object again (i.e. via `__init__` or a dedicated loading `classmethod`). Large data object will also slow down module startup considerably.
- Without taking special care to make a class "yaml-compatible" by having dedicated dumper/loader methods or ensuring ALL data members are compatible, `yaml_object` will also not help. In my opinion this would only create a false sense of security and make the requirements for a `StatusVar` type more ambiguous (sometimes it works, sometimes not). Currently you at least know for sure, you need to convert objects for dumping/loading. KISS principle applies here.
- I had the case that a failed dump attempt on a class registered with `yaml_object` rendered the `YAML` instance non-functional. So if `qudi` would keep a single instance in order to register classes from anywhere, it would break the yaml functionality for the entire application on a failed dump attempt. Currently `qudi` is keeping a customized `YAML` class instead and creates instances on each dump/load call (more robust).

Regarding `dataclass`:
You are technically correct, however many decorators "tag" the object they act upon. In case of `dataclass` there is even a library function to check for the decorator:
```Python
from dataclasses import is_dataclass, dataclass

@dataclass()
class MyData:
    foo: int
    bar: str

if __name__ == '__main__':
    data = MyData(42, 'fancy data')
    assert(is_dataclass(data))
    assert(is_dataclass(MyData))
```
So my proposal would in principle work.

**Comment by Neverhorst** [comment]
If someone (like yourself for example) wants to extend the qudi yaml dumping/loading in custom code, they can simply do:
```Python
from qudi.util.yaml import YAML
from ruamel.yaml import yaml_object

yaml = YAML()

@yaml_object(yaml)
class MyData:
    ...
```
and customize away registering additional objects on an instance without breaking anything in the qudi core.

**Comment by qku** [comment]
I found a nice solution to my problem of dumping and loading a dataclass as a `StatusVar`. [`dataclasses.asdict`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) is really useful as it converts a dataclass to a dictionary and also recurses into nested dataclasses. Reconstruction is almost as simple: `MyDataclass(**dumped_dict)` works if you don't have nested dataclasses. If you do, you need to take care of these separately which is fair though I guess.

**Comment by Fatal1ty** [comment]
> Reconstruction is almost as simple: MyDataclass(**dumped_dict) works if you don't have nested dataclasses. If you do, you need to take care of these separately which is fair though I guess.

Hey guys. You can also entrust this care to a third-party library like [mashumaro](https://github.com/Fatal1ty/mashumaro). All you have to do in this case is inherit [DataClassYAMLMixin](https://github.com/Fatal1ty/mashumaro#dataclassyamlmixin) in your root dataclass.
